[glassnote_api]
api_key = '23xKyUhf3J2dYGXBD2tgsYkvjrv'
[messary_api]
x-messari-api-key="77fd912b-7c49-449f-a808-d3755b9bb69a"
[stauth]
names = ['Tensor']
usernames = ['tech@tensorcorp.com']
passwords = ['TensorCorp888!']